### ISSUE TITLE
[minor] Unnecessary second term

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/reactNativeChallenge#10]
In this case you should use the `&&` operator, as you don't need the second term used in ternary operations

https://github.com/donpapitoskey/reactNativeChallenge/blob/6e833662e2a65105a3b9c5926ac6f327ddba8539/components/searchField/SearchField.js#L71

**Comment by donpapitoskey** [comment]
Noted. Ternary replaced with `&&` for conditional
