### ISSUE TITLE
[minor] Usage of external function

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/reactNativeChallenge#12]
As this function's only use is to call another function, you should call it directly inline instead of creating a useless one

https://github.com/donpapitoskey/reactNativeChallenge/blob/6e833662e2a65105a3b9c5926ac6f327ddba8539/screens/charactersListScreen/CharactersListScreen.js#L35

**Comment by donpapitoskey** [comment]
Noted. Functions only used when usefull
