### ISSUE TITLE
[minor] Missing error

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/reactNativeChallenge#13]
You should probably do something with the catched exception, even maybe logging it into the console, if you don't need the error for the message

https://github.com/donpapitoskey/reactNativeChallenge/blob/6e833662e2a65105a3b9c5926ac6f327ddba8539/screens/charactersListScreen/CharactersListScreen.js#L60

**Comment by donpapitoskey** [comment]
Noted. Logging error to console.
