### ISSUE TITLE
[minor] Unnecesary else

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/reactNativeChallenge#15]
When returning elements in a function with `if` blocks, you don't need the `else` block at the end

https://github.com/donpapitoskey/reactNativeChallenge/blob/6e833662e2a65105a3b9c5926ac6f327ddba8539/screens/detailsScreen/DetailsScreen.js#L13

**Comment by donpapitoskey** [comment]
Noted. Unnecesary else deleted
