### ISSUE TITLE
[minor] Object assignment shorthand

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/reactNativeChallenge#2]
When assigning a value to a key of an object with the same name, you don't need to repeat it, with only writing one word you can shorthand key-value pairs of the same name

https://github.com/donpapitoskey/reactNativeChallenge/blob/6e833662e2a65105a3b9c5926ac6f327ddba8539/components/CustomText/CustomText.js#L7

**Comment by donpapitoskey** [comment]
Noted and fixed
