### ISSUE TITLE
[CRITICAL] Non-boolean conditionals

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/reactNativeChallenge#3]
Never use non-boolean values for a condition of this kind. By using the `&&` operator, you're telling that you're rendering both objects, something that can become a serious threat.

https://github.com/donpapitoskey/reactNativeChallenge/blob/6e833662e2a65105a3b9c5926ac6f327ddba8539/components/card/Card.js#L13

**Comment by donpapitoskey** [comment]
Fixed. Boolean condition created for rendering compoments
