### ISSUE TITLE
[minor] Implicit return usage

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/reactNativeChallenge#4]
When everything in your arrow function is returned, you can take advantage of implicit return to avoid having to explicitly declare it.

https://github.com/donpapitoskey/reactNativeChallenge/blob/6e833662e2a65105a3b9c5926ac6f327ddba8539/components/error/Error.js#L6

**Comment by donpapitoskey** [comment]
Noted. Implicit return used whenever possible
