### ISSUE TITLE
[suggestion] Using a single Text component

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/reactNativeChallenge#5]
I can see here that you used the exact same components to render three lines of code. I suggest you to handling the line break inside a single Text component to avoid unnecessary components

https://github.com/donpapitoskey/reactNativeChallenge/blob/6e833662e2a65105a3b9c5926ac6f327ddba8539/components/error/Error.js#L8

**Comment by donpapitoskey** [comment]
Noted. Fixed for Error Component
