### ISSUE TITLE
[minor] Style merging

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/reactNativeChallenge#6]
The correct way of merging various styles is using an array, e.g. `[style, styles.buttonContainer]`

https://github.com/donpapitoskey/reactNativeChallenge/blob/6e833662e2a65105a3b9c5926ac6f327ddba8539/components/initButton/InitButton.js#L11

**Comment by donpapitoskey** [comment]
Noted. Various styles merging solved with array, rather than object
