### ISSUE TITLE
[minor] Message rendering

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/reactNativeChallenge#7]
So, to fix many things here, first you should make an external function to return the message needed for this component. Next, you should use `if` blocks, to make the code more readable, instead of ternaries which are not needed in this case. Lastly, as the only part of the message which is changing is the second part, you should do a method to use the first part as a fixed value and append the second part.

https://github.com/donpapitoskey/reactNativeChallenge/blob/6e833662e2a65105a3b9c5926ac6f327ddba8539/components/resultsText/ResultsText.js#L9

**Comment by donpapitoskey** [comment]
Noted. External function implemented, using `if` for readability and  appending text
