### ISSUE TITLE
[suggestion] Method naming

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/reactNativeChallenge#9]
OnSearch is the event in which a callback is triggered. A more convenient name should be `searchHandler` or the function's usage, e.g. `searchEntities`

https://github.com/donpapitoskey/reactNativeChallenge/blob/6e833662e2a65105a3b9c5926ac6f327ddba8539/components/searchField/SearchField.js#L43

**Comment by donpapitoskey** [comment]
Noted. Using more descriptive names for functions
